#database connection for points
database:
  host: localhost
  port: 3306
  database-name: dbname
  user: username
  password: password

#mob settings

#time in hours before mobs' damage start increasing
#default: 72, 0 disables
multiplier-time: 72

#max multiplier value
#default 3.0, 0 is no max
max-multiplier: 3.0

#items that can be bought with points
buyables:
  life: 500
  diamond: 15
  copper_ingot: 3
  emerald: 5
  iron_ingot: 8
  gold_ingot: 10
  redstone: 1
  lapis_lazuli: 1
  oak_sapling: 5
  birch_sapling: 4
  spruce_sapling: 4
  jungle_sapling: 8
  acacia_sapling: 4
  dark_oak_sapling: 1
  melon_seeds: 5
  pumpkin_seeds: 5
  wheat_seeds: 1
  carrot: 3
  potato: 3
  beetroot_seeds: 3
  golden_carrot: 5
  sugar_cane: 1
  bamboo: 10
  moss_block: 15
  chorus_fruit: 20
  sweet_berries: 10
  glow_berries: 15
  cocoa_beans: 5
  zombie_spawn_egg: 30
  zombie_villager_spawn_egg: 55
  skeleton_spawn_egg: 50
  creeper_spawn_egg: 50
  blaze_spawn_egg: 60
  ghast_spawn_egg: 50
  wither_skeleton_spawn_egg: 65
  piglin_spawn_egg: 40
  zombified_piglin_spawn_egg: 55
  axolotl_spawn_egg: 12.5
  sheep_spawn_egg: 12.5
  cow_spawn_egg: 25
  pig_spawn_egg: 10
  chicken_spawn_egg: 5
  villager_spawn_egg: 50
  cat_spawn_egg: 15
  wolf_spawn_egg: 15
  parrot_spawn_egg: 20
  slime_spawn_egg: 40
  spider_spawn_egg: 25
  cave_spider_spawn_egg: 30
  evoker_spawn_egg: 30
  pillager_spawn_egg: 35
  piglin_brute_spawn_egg: 35
  fox_spawn_egg: 20
  phantom_spawn_egg: 25
  squid_spawn_egg: 20
  glow_squid_spawn_egg: 25
  horse_spawn_egg: 20
  donkey_spawn_egg: 25
  polar_bear_spawn_egg: 15
  shulker_spawn_egg: 45
  witch_spawn_egg: 55
  wandering_trader_spawn_egg: 50
  turtle_spawn_egg: 18
  vindicator_spawn_egg: 40
  strider_spawn_egg: 20
  rabbit_spawn_egg: 12.5
  silverfish_spawn_egg: 10
  goat_spawn_egg: 12.5
  bee_spawn_egg: 16
  panda_spawn_egg: 12.5
  hoglin_spawn_egg: 40
  zoglin_spawn_egg: 35
  cobblestone: 0.05
  flowering_azalea: 12
  kelp: 0.1
  soul_sand: 5
  nether_wart: 10
  glass: 1
  tinted_glass: 2
  ice: 1
  packed_ice: 5
  blue_ice: 9
  clay: 2
  snow_block: 0.5
  beacon: 90
  sand: 0.5
  blackstone: 0.2
  cobweb: 1
  weeping_vines: 2
  twisting_vines: 2
  sea_pickle: 4
  cactus: 2
  torch: 0.2
  lily_pad: 0.5
  enchanting_table: 35
  glow_lichen: 1
  vine: 1
  shulker_shell: 12
  glowstone: 5
  shroomlight: 5
  tnt: 2
  wither_skeleton_skull: 20
  ender_pearl: 8
  blaze_powder: 4
  diamond_horse_armor: 20
  name_tag: 20
  totem_of_undying: 70
  trident: 50
  dirt: 0.1
  gravel: 0.5
  deepslate: 0.1
  spawner: 45
  lead: 10
  saddle: 25
  guardian_spawn_egg: 55
