#database connection for points
database:
  host: localhost
  port: 3306
  database-name: dbname
  user: username
  password: password

#mob settings

#time in hours before mobs' damage start increasing
#default: 72, 0 disables
multiplier-time: 72

#max multiplier value
#default 3.0, 0 is no max
max-multiplier: 3.0

#items that can be bought with points
#can specify own custom categories and the items listed per category

#TODO allow multiple depths
buyables:
  Miscellaneous:
    life: 500
    beacon: 65
    totem_of_undying: 70
    diamond_horse_armor: 10
    name_tag: 8
    spawner: 40
    lead: 5
    saddle: 10
    oak_boat: 1
    nautilus_shell: 8
    heart_of_the_sea: 5
    pointed_dripstone: 0.5
  Gems/Ingots:
    diamond: 12
    copper_ingot: 0.5
    emerald: 3
    iron_ingot: 3
    gold_ingot: 6
    lapis_lazuli: 0.5
    quartz: 0.5
    netherite_scrap: 9
    amythest_shard: 0.5
    coal: 0.1
  Plants/Food:
    oak_sapling: 0.5
    birch_sapling: 0.5
    spruce_sapling: 0.5
    jungle_sapling: 2
    acacia_sapling: 0.5
    dark_oak_sapling: 0.5
    melon_seeds: 3
    pumpkin_seeds: 3
    wheat_seeds: 0.1
    carrot: 2
    potato: 2
    beetroot_seeds: 1
    golden_carrot: 2
    golden_apple: 5
    sugar_cane: 0.5
    bamboo: 4
    moss_block: 4
    chorus_fruit: 6
    sweet_berries: 2
    glow_berries: 4
    cocoa_beans: 3
    flowering_azalea: 3
    kelp: 0.1
    nether_wart: 8
    weeping_vines: 1
    twisting_vines: 1
    sea_pickle: 2
    cactus: 2
    lily_pad: 0.5
    glow_lichen: 1
    vine: 1
    brown_mushroom: 2
    red_mushroom: 2
    crimson_fungus: 3
    warped_fungus: 3
    wither_rose: 5
  Eggs:
    zombie_spawn_egg: 30
    zombie_villager_spawn_egg: 55
    skeleton_spawn_egg: 45
    creeper_spawn_egg: 50
    blaze_spawn_egg: 60
    ghast_spawn_egg: 50
    wither_skeleton_spawn_egg: 65
    piglin_spawn_egg: 40
    zombified_piglin_spawn_egg: 50
    axolotl_spawn_egg: 5
    sheep_spawn_egg: 10
    cow_spawn_egg: 15
    pig_spawn_egg: 8
    chicken_spawn_egg: 4
    villager_spawn_egg: 50
    cat_spawn_egg: 4
    wolf_spawn_egg: 6
    parrot_spawn_egg: 5
    slime_spawn_egg: 35
    spider_spawn_egg: 15
    cave_spider_spawn_egg: 20
    evoker_spawn_egg: 30
    pillager_spawn_egg: 35
    illager_spawn_egg: 40
    piglin_brute_spawn_egg: 30
    fox_spawn_egg: 10
    phantom_spawn_egg: 20
    squid_spawn_egg: 20
    glow_squid_spawn_egg: 20
    horse_spawn_egg: 20
    donkey_spawn_egg: 20
    polar_bear_spawn_egg: 10
    shulker_spawn_egg: 45
    witch_spawn_egg: 55
    wandering_trader_spawn_egg: 45
    turtle_spawn_egg: 15
    vindicator_spawn_egg: 40
    strider_spawn_egg: 10
    rabbit_spawn_egg: 10
    silverfish_spawn_egg: 5
    goat_spawn_egg: 10
    bee_spawn_egg: 10
    panda_spawn_egg: 10
    hoglin_spawn_egg: 35
    zoglin_spawn_egg: 30
    guardian_spawn_egg: 55
  Building:
    cobblestone: 0.05
    soul_sand: 5
    glass: 0.5
    tinted_glass: 2
    ice: 1
    packed_ice: 5
    blue_ice: 9
    clay: 0.5
    snow_block: 0.05
    sand: 0.5
    red_sand: 0.5
    blackstone: 0.1
    dirt: 0.05
    gravel: 0.1
    tuff: 0.1
    calcite: 1
    diorite: 0.05
    andesite: 0.05
    granite: 0.05
    mycelium: 1
    netherrack: 0.01
    podzol: 0.2
    dripstone_block: 0.1
    sponge: 3
    bookshelf: 6
    basalt: 0.01
    magma_block: 0.2
    obsidian: 3
    gilded_blackstone: 4
    crying_obsidian: 2
    soul_soil: 1
    crimson_nylium: 1.5
    warped_nylium: 1.5
  Decorative:
    cobweb: 1
    enchanting_table: 25
    end_portal_frame: 5
    blast_furnace: 1
    furnace: 0.1
    crafting_table: 0.1
    smoker: 1
    composter: 0.5
    cartography_table: 1
    fletching_table: 1
    grindstone: 1
    smithing_table: 1
    stonecutter: 1
  MobDrops:
    shulker_shell: 12
    wither_skeleton_skull: 16
    ender_pearl: 6
    blaze_rod: 5
    arrow: 0.5
    rotten_flesh: 0.1
    spider_eye: 0.5
    bone: 0.5
    string: 0.5
    prismarine_shard: 1
    prismarine_crystals: 2
    phantom_membrane: 2
    leather: 0.5
    white_wool: 0.5
    raw_beef: 1
    egg: 0.5
    feather: 1
    ink_sac: 1
    pufferfish: 1
    cod: 1
    salmon: 1
    tropical_fish: 1
    glow_ink: 1
    rabbit_foot: 1
    rabbit_hide: 1
  Lighting:
    glowstone: 5
    shroomlight: 5
    torch: 0.2
    redstone_lamp: 0.2
    sea_lantern: 0.2
  Redstone:
    redstone: 0.5
    sticky_piston: 2
    piston: 1
    tnt: 2
    redstone_repeater: 1
    redstone_comparator: 1
    observer: 2
    slime_block: 1
    honey_block: 1
    hopper: 1
    dispenser: 1
    dropper: 1
    redstone_torch: 1
    daylight_detector: 1
  Tools:
    diamond_pickaxe: 35
    diamond_sword: 25
    diamond_shovel: 10
    diamond_axe: 30
    diamond_hoe: 20
    trident: 50
    bow: 5
    crossbow: 5
    shield: 1
    turtle_helmet: 5
    diamond_helmet: 25
    diamond_chestplate: 35
    diamond_leggings: 30
    diamond_boots: 25
    shears: 2
    fishing_rod: 1
    flint_and_steel: 1